### ISSUE TITLE
Error in homebridge and within myQ app

### ISSUE THREAD

**Issue by cjkuhlenbeck** [hjdhjd/homebridge-myq#627] opened 2022-01-28 08:57 UTC
Getting a repeated error, but I don't think it's from the plugin as much as the server. The error from the log is:

```
[Garage Door] myQ API: https://partner-identity.myq-cloud.com/connect/authorize?client_id=IOS_CGI_MYQ&code_challenge=D8I-gKRqxDhjr9AUf-au5yyr34WnRhxZ2NdJydaFMaU&code_challenge_method=S256&redirect_uri=com.myqops%3A%2F%2Fios&response_type=code&scope=MyQ_Residential+offline_access Error: 400 Bad Request
[Garage Door] myQ API: Unable to access the OAuth authorization endpoint.
```

The error comes up immediately on startup, and no devices are added. I'm also getting an error within the MyQ app though which is why I believe it may not be tied to the plugin specifically. The error within the app is ReturnCode -99 and then a random support ID:
```
{
    "ReturnCode": "-99",
    "ErrorMessage": "please contact customer care, supportID: 16840261738340799954",
    "CorrelationId": ""
}
```

Has anyone come across this yet? I tried reaching out to MyQ support, but after 4 hours and suggesting I delete and reinstall the app 4 times (seriously) and reboot my network 3 times, they advised they would call me back in a few days.

* **Homebridge Version:** 1.4.0
* **Node Version:** 16.13.2
* **Homebridge-myQ Plugin Version**: 2.7.4
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**iPad Pro 3rd gen and iPhone 12 Pro Max running 15.2.1

**Comment by hjdhjd** [comment] 2022-01-28 09:44
Occasional API errors happen…it’s par for the course in myQ. This isn’t a plugin issue I’m afraid.

**Comment by cjkuhlenbeck** [comment] 2022-01-28 23:14
> Occasional API errors happen…it’s par for the course in myQ. This isn’t a plugin issue I’m afraid.

I figured as much :( Any possible tips on getting it running again? It's been like this for 2 weeks now, and MyQ support really is useless at this point, so hoping for solutions from other sources :D

**Comment by Beartech** [comment] 2022-02-05 02:09
Still not working. This isn't an occasional API error. MyQ has probably broken something. How is that not a plugin issue?

**Comment by hjdhjd** [comment] 2022-02-05 02:46
Because it works fine for virtually everyone else. Look into resetting your account, changing your password, etc. There isn’t much I can do to help you on this one I’m afraid. I’d suggest trying the Discord as well for any tips other people might have…this isn’t a plugin problem. 

Historically, these issues boil down to either an account-related issue or something that isn’t configured correctly at the network level. Not being able to get the OAuth authorization endpoint means the plugin isn’t able to retrieve certain webpages it needs to login. That could mean DNS issues, if you’re using an ad-filtering DNS or firewall that can cause a problem, etc…all these things can have an impact.

Finally, there’s the age-old, uninstall and reinstall the plugin…something may have been funky in your specific installation.

None of the above is a panacea or a clear answer and I’m sure it’s frustrating as a user. Please understand that it’s equally frustrating to receive declarations that insist there is a problem in a plugin that is used by thousands of people - successfully - every single day. If there’s a plugin issue, great…let’s fix it, but it’s unlikely that’s the issue here.

**Comment by 3ne** [comment] 2022-02-05 03:08
Seeing the same issue, it’s definitely server side. Can’t even login via browser.

**Comment by rkeniger** [comment] 2022-02-05 03:27
I’m also seeing this.

**Comment by Beartech** [comment] 2022-02-05 03:39
@3ne I can log into the website and the phone app no problem. This has been going on since an update around end of December/beginning of January. I updated the MyQ plugin and it then crashed my Hombridge non stop. So I wiped and updated to the latest homebridge. Completely deleted everything and reinstalled. Homebridge has perfect access to the internet, it can talk to the outside world no problem.

**Comment by 3ne** [comment] 2022-02-05 03:41
> @3ne I can log into the website and the phone app no problem. This has been going on since an update around end of December/beginning of January. I updated the MyQ plugin and it then crashed my Hombridge non stop. So I wiped and updated to the latest homebridge. Completely deleted everything and reinstalled. Homebridge has perfect access to the internet, it can talk to the outside world no problem. 

Man it's weird, I can't login via app or website. It only started today, in fact I only noticed a few hrs ago.

**Comment by hjdhjd** [comment] 2022-02-05 03:45
Given history, entirely possible they’re doing maintenance on the myQ end. Try it tomorrow…see what happens. Yeah, all these answers aren’t great, but we’re dealing with a not great API and backend in the first place. :smile:

**Comment by cjkuhlenbeck** [comment] 2022-02-05 03:46
I'm pretty sure it's server side as originally advised. I believe it's a server side IP ban from MyQ/Chamberlain; likely from too many API requests from the plugin.

As to other people, it can't be just the plugin as it affects the app as well (if you're not seeing the error in the app, make sure you're on the same Wi-Fi on your phone, and not using a VPN or private relay). As long as you're on the same network, the MyQ app will error out before you can do anything including login.

**Comment by 3ne** [comment] 2022-02-05 03:47
> Given history, entirely possible they’re doing maintenance on the myQ end. Try it tomorrow…see what happens. Yeah, all these answers aren’t great, but we’re dealing with a not great API and backend in the first place. 😄

It’s all good @hjdhjd , I know it has nothing to do with the plug-in.

**Comment by 3ne** [comment] 2022-02-05 03:48
> I'm pretty sure it's server side as originally advised. I believe it's a server side IP ban from MyQ/Chamberlain; likely from too many API requests from the plugin.
> 
> As to other people, it can't be just the plugin as it affects the app as well (if you're not seeing the error in the app, make sure you're on the same Wi-Fi on your phone, and not using a VPN or private relay). As long as you're on the same network, the MyQ app will error out before you can do anything including login.

Correct

**Comment by cjkuhlenbeck** [comment] 2022-02-05 03:52
> > I'm pretty sure it's server side as originally advised. I believe it's a server side IP ban from MyQ/Chamberlain; likely from too many API requests from the plugin.
> > As to other people, it can't be just the plugin as it affects the app as well (if you're not seeing the error in the app, make sure you're on the same Wi-Fi on your phone, and not using a VPN or private relay). As long as you're on the same network, the MyQ app will error out before you can do anything including login.
> 
> Correct

3ne, from my troubleshooting, it seems like changing the IP is the way to go but my ISP doesnt allow IP changing to confirm. Most of the time it's done via a simple reset of the router. Can you try whatsmyip and reboot the router to see if it changes the public IP, and if so resolves the error?

**Comment by shamoon** [comment] 2022-02-05 05:05
Hard to say if its IP banning or their flakiness but I think its the latter (I suppose maybe both, maybe theyre getting DDoS'd?). I think its specifically the oauth endpoint e.g.partner-identity.myq-cloud.com

See https://downdetector.com/status/myq/ & https://downforeveryoneorjustme.com/partner-identity.myq-cloud.com?proto=http
<img width="750" alt="Screen Shot 2022-02-04 at 9 05 08 PM" src="https://user-images.githubusercontent.com/4887959/152629447-1714dee1-bb2f-41ab-bbb1-725ffe3e17df.png">
s

**Comment by cjkuhlenbeck** [comment] 2022-02-05 08:19
> Hard to say if its IP banning or their flakiness but I think its the latter (I suppose maybe both, maybe theyre getting DDoS'd?). I think its specifically the oauth endpoint e.g.partner-identity.myq-cloud.com
> 
> See https://downdetector.com/status/myq/ & https://downforeveryoneorjustme.com/partner-identity.myq-cloud.com?proto=http <img alt="Screen Shot 2022-02-04 at 9 05 08 PM" width="750" src="https://user-images.githubusercontent.com/4887959/152629447-1714dee1-bb2f-41ab-bbb1-725ffe3e17df.png"> s

Maybe both. But I can say my issue has been going on for weeks and not just today. As some others mentioned, it started back in December. That would be a long DDOS attack.

**Comment by Beartech** [comment] 2022-02-05 17:21
> But I can say my issue has been going on for weeks and not just today. As some others mentioned, it started back in December

Same here. Did and update to just MyQ and it has never worked since. Like I said, did all of the usual troubleshooting and even a complete wipe and rebuild. Don't get me wrong, I appreciate all the work that went into this. I didn't know until now that Chamberlain was that flaky. Now that I know it, I'm just done with Chamberlain. I'm not going to buy their $70 unit jus to get something that is already on my wifi network to connect to HomeKit. Going to just wire it to a wifi switch and rig up a position sensor for the door. Thank you for the work on this plugin.

**Comment by hjdhjd** [comment] 2022-02-05 17:31
Try reverting to prior versions, if you think that's the true cause and see if things work...I'm generally skeptical that there's something there. Correlation isn't causation, and we as humans tend to associate things with each other because we like patterns. 

That said, there's nothing like some old fashioned A/B testing to see if there really is an issue or not. The Homebridge UI makes it easy to revert to prior versions of any of the plugins.

If there's a plugin issue, let's find it. If there isn't...well...something has to be the cause of some of you struggling and others not. If the native myQ app is working, the plugin should absolutely work. If the native myQ app isn't working, you've got something else going on with the Liftmaster/Chamberlain world. That's essentially the gold standard here and the "one true test" of whether things are working or not.

**Comment by hjdhjd** [comment] 2022-02-05 18:19
> > But I can say my issue has been going on for weeks and not just today. As some others mentioned, it started back in December
> 
> Same here. Did an update to just MyQ and it has never worked since. Like I said, did all of the usual troubleshooting and even a complete wipe and rebuild. Don't get me wrong, I appreciate all the work that went into this. I didn't know until now that Chamberlain was that flaky. Now that I know it, I'm just done with Chamberlain. I'm not going to buy their $70 unit jus to get something that is already on my wifi network to connect to HomeKit. Going to just wire it to a wifi switch and rig up a position sensor for the door. Thank you for the work on this plugin.

Good luck...that's a lot of additional failure points in my experience...but I'm always interested in new ways of doing things and sincerely curious. In my experience, myQ has been generally reliable...say a 90% hit rate. Yeah, the 10% is annoying...but all the alternatives suck at least as much, if not more, and these guys essentially own the garage door opener market (at least here in the States). It will suck less over time...the service has certainly improved over the years, but it's a long way from 5-9s in availability. :smile:

**Comment by 3ne** [comment] 2022-02-05 19:11
We're back in business

**Comment by cjkuhlenbeck** [comment] 2022-02-05 19:12
> We're back in business

Did a new IP resolve it? I'm still out here with the same error.

**Comment by Beartech** [comment] 2022-02-05 19:23
I actually tried all of that. The app works perfect right now. 

It's just no longer worth my time. It is the only MyQ hardware I have and I'll never give them another cent of my money. Generic HomeKit compatible openers are available for $40 on Amazon. Order one already and will have it tomorrow. 

Good luck!

**Comment by Beartech** [comment] 2022-02-05 19:28
For anyone looking for a direct HomeKit solution: 
https://www.amazon.com/gp/product/B08GG1H7TV/ref=ppx_od_dt_b_asin_title_s00?ie=UTF8&psc=1
I preferred my old z-wave opener but there is only one solution that is repacked under other names, it's over $50, and it fails after a few years due to an LED getting overpowered.

**Comment by hjdhjd** [comment] 2022-02-05 19:34
Or just by the myQ Home Bridge for another $10-20? :smile:

**Comment by Beartech** [comment] 2022-02-05 21:59
$10-20? Show me a link. It is $99 on amazon and $70 if you buy it from MyQ website.

**Comment by shamoon** [comment] 2022-02-06 01:18
> We're back in business

Yea mine too as of last night, I’m guessing there is more than one issue being discussed here but for many of us seems it was just server unreliability as theorized. (My IP never changed FYI)

**Comment by hjdhjd** [comment] 2022-02-06 01:19
Great...closing the issue. Thanks all.

**Closed by hjdhjd** 2022-02-06 01:19 UTC
