### ISSUE TITLE
myQ API: Unable to access the OAuth authorization endpoint.

### ISSUE THREAD

**Issue by mmiller0** [hjdhjd/homebridge-myq#284] opened 2021-02-22 15:36 UTC
**Describe The Problem:**
Unable to access myQ via Homebridge due to near constant oauth errors. Reverting back to v2.4.2 of the plugin resolves the issue and allows the devices to be controlled. This has been happening since 20 Feb 2021.

**To Reproduce:**
Install v2.6.1 or later of the plugin. Every few hours the auth works for a few minutes, but then returns to near constant error logging.

**Logs:**
[22/02/2021, 06:57:05] [myQ] myQ API: https://partner-identity.myq-cloud.com/connect/authorize?client_id=IOS_CGI_MYQ&code_challenge=ZwcimM4qXTSCIs7mdyDLBEV1VPIGqIq_OeEZrWJc-lc&code_challenge_method=S256&redirect_uri=com.myqops%3A%2F%2Fios&response_type=code&scope=MyQ_Residential+offline_access Error: 400 Bad Request
[22/02/2021, 06:57:05] [myQ] myQ API: Unable to access the OAuth authorization endpoint. Will retry later.
[22/02/2021, 06:59:05] [myQ] myQ API: https://partner-identity.myq-cloud.com/connect/authorize?client_id=IOS_CGI_MYQ&code_challenge=ylWvdmUwTaWR_DlL5YsnKM3zTgOEQKwmcswt8zCZ2kk&code_challenge_method=S256&redirect_uri=com.myqops%3A%2F%2Fios&response_type=code&scope=MyQ_Residential+offline_access Error: 400 Bad Request
[22/02/2021, 06:59:05] [myQ] myQ API: Unable to access the OAuth authorization endpoint. Will retry later.
[22/02/2021, 07:01:06] [myQ] myQ API: https://partner-identity.myq-cloud.com/connect/authorize?client_id=IOS_CGI_MYQ&code_challenge=F7hWsv1VBXyl2pOSBtDaw6KZWgRddDtpmCIjDru_RHU&code_challenge_method=S256&redirect_uri=com.myqops%3A%2F%2Fios&response_type=code&scope=MyQ_Residential+offline_access Error: 400 Bad Request
[22/02/2021, 07:01:06] [myQ] myQ API: Unable to access the OAuth authorization endpoint. Will retry later.
[22/02/2021, 07:03:07] [myQ] myQ API: https://partner-identity.myq-cloud.com/connect/authorize?client_id=IOS_CGI_MYQ&code_challenge=bneJCo7fpYyknY-VEmtC-V34KWBoD07EcGlAIG7fUOs&code_challenge_method=S256&redirect_uri=com.myqops%3A%2F%2Fios&response_type=code&scope=MyQ_Residential+offline_access Error: 400 Bad Request
[22/02/2021, 07:03:07] [myQ] myQ API: Unable to access the OAuth authorization endpoint. Will retry later.
[22/02/2021, 07:05:08] [myQ] myQ API: https://partner-identity.myq-cloud.com/connect/authorize?client_id=IOS_CGI_MYQ&code_challenge=z9vIzN-WL3onOvaFvy8l8LXd30KPDyhRRDyk9XFU0WU&code_challenge_method=S256&redirect_uri=com.myqops%3A%2F%2Fios&response_type=code&scope=MyQ_Residential+offline_access Error: 400 Bad Request
[22/02/2021, 07:05:08] [myQ] myQ API: Unable to access the OAuth authorization endpoint. Will retry later.
[22/02/2021, 07:07:09] [myQ] myQ API: https://partner-identity.myq-cloud.com/connect/authorize?client_id=IOS_CGI_MYQ&code_challenge=Iq5DRf5KmJZOJNxxsijA7JYNQABmwsK7mMcjj6E4eJE&code_challenge_method=S256&redirect_uri=com.myqops%3A%2F%2Fios&response_type=code&scope=MyQ_Residential+offline_access Error: 400 Bad Request
[22/02/2021, 07:07:09] [myQ] myQ API: Unable to access the OAuth authorization endpoint. Will retry later.
[22/02/2021, 07:09:09] [myQ] myQ API: https://partner-identity.myq-cloud.com/connect/authorize?client_id=IOS_CGI_MYQ&code_challenge=nCANlpZ8gaIp7xemi3vcwzWjR6HmAFC7VVK_IOm7uVM&code_challenge_method=S256&redirect_uri=com.myqops%3A%2F%2Fios&response_type=code&scope=MyQ_Residential+offline_access Error: 400 Bad Request
[22/02/2021, 07:09:09] [myQ] myQ API: Unable to access the OAuth authorization endpoint. Will retry later.
[22/02/2021, 07:11:09] [myQ] myQ API: https://partner-identity.myq-cloud.com/connect/authorize?client_id=IOS_CGI_MYQ&code_challenge=AkWXJkVCX75rQqLvRAMMcITZ9pYMmcajJBY73vsDT6o&code_challenge_method=S256&redirect_uri=com.myqops%3A%2F%2Fios&response_type=code&scope=MyQ_Residential+offline_access Error: 400 Bad Request
[22/02/2021, 07:11:09] [myQ] myQ API: Unable to access the OAuth authorization endpoint. Will retry later.
[22/02/2021, 07:13:10] [myQ] myQ API: https://partner-identity.myq-cloud.com/connect/authorize?client_id=IOS_CGI_MYQ&code_challenge=ky9WosiNWKa4NVa8uTS_WpBxzOCf_KujjVObSd6FHJU&code_challenge_method=S256&redirect_uri=com.myqops%3A%2F%2Fios&response_type=code&scope=MyQ_Residential+offline_access Error: 400 Bad Request
[22/02/2021, 07:13:10] [myQ] myQ API: Unable to access the OAuth authorization endpoint. Will retry later.

**Homebridge Configuration:**

        {
            "email": "xxxxxxxxxx
            "password": "yyyyyyyyy",
            "refreshInterval": 15,
            "platform": "myQ"
        }

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.3.0
* **Node Version:** v14.15.4
* **Homebridge-myQ Plugin Version**: 2.6.2
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** macOS 11.2.1, iOS 14.4, iPadOS 14.4
* **Operating System and OS Version:** Raspbian GNU/Linux Buster (10)

**Comment by hjdhjd** [comment] 2021-02-22 15:39
Duplicate of #276

**Closed by hjdhjd** 2021-02-22 15:39 UTC

**Comment by mmiller0** [comment] 2021-02-22 15:48
FWIW I agree this is a duplicate, however v2.4.2 of the plugin is working while 2.6.2 is not (I reverted / restored to latest a few times to ensure this was the case). That seems like useful information which can not be posted to the original issue due to it being locked.

**Comment by hjdhjd** [comment] 2021-02-22 15:51
Thanks...I'm aware. I doubt it's going to work for too many more weeks at this point, as their API transition is coming to the finish line and I'm sure they're going to eliminate the old API as soon as possible.
