### ISSUE TITLE
Activity Notifications and History Not Displaying

### ISSUE THREAD

**Issue by victormarte** [hjdhjd/homebridge-myq#1131] opened 2023-10-19 15:49 UTC
**Describe The Problem:**

**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-myQ Plugin Version**:
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by ghosilyk** [comment] 2023-10-20 04:10
It's even worse for me, it started that way, but now I can't even control my garage. I'm getting an API locked out error, yet the regular MyQ app works so my account doesn't appear to be locked out.

**Comment by JerryLujy** [comment] 2023-10-20 04:15
I'm getting `[myQ] myQ API error: Temporary myQ API server-side issues encountered: 429 - Too Many Requests. This typically indicates a myQ API lockout for a 60-90 minute period before resuming API connectivity.`. Not sure if related.

**Comment by jchilders99** [comment] 2023-10-20 13:26
Just hoping on the thread to say "same".  MyQ app works, but I'm receiving the API lockout error in Homebridge.

**Comment by hjdhjd** [comment] 2023-10-20 13:28
As stated elsewhere...yep, myQ has made some additional changes. We will work to adapt. Closing this, given it's duplicate of other issues.

**Closed by hjdhjd** 2023-10-20 13:28 UTC
