### ISSUE TITLE
myQ API error: Forbidden API call. This error is typically due to an offline or unavailable myQ device.

### ISSUE THREAD

**Issue by TottiUno** [hjdhjd/homebridge-myq#1103] opened 2023-09-08 23:27 UTC
**Describe The Problem:**
myQ API error: Forbidden API call. This error is typically due to an offline or unavailable myQ device.

<img width="879" alt="image" src="https://github.com/hjdhjd/homebridge-myq/assets/144498401/8d099edd-172a-4655-aaf4-199e36a3359a">

**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**
<img width="879" alt="image" src="https://github.com/hjdhjd/homebridge-myq/assets/144498401/34871aae-8b90-4afc-9ecf-2b86421b6b3b">

**Environment:**

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-myQ Plugin Version**:
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by TottiUno** [comment] 2023-09-08 23:27
Not able to login

**Comment by zwoop** [comment] 2023-09-08 23:33
I'm seeing the same, and my login / password works fine in the MyQ app itself.

**Comment by mweckmann** [comment] 2023-09-08 23:43
Same here. MYQ App works fine. I tried logging out and in with no success.

**Comment by 9zero8** [comment] 2023-09-08 23:47
Same on my end.  MYQ App works though.

**Comment by razholio** [comment] 2023-09-08 23:47
Add me to the list.  Auth verified.

**Comment by Guy559** [comment] 2023-09-08 23:52
Same. No longer working on Homebridge or Home Assistant. Receiving the following:

[9/8/2023, 6:49:13 PM] [myQ] myQ API error: Forbidden API call. This error is typically due to an offline or unavailable myQ device.

**Comment by mdjhnson** [comment] 2023-09-08 23:57
I'm not sure if MyQ changed their cloud access. I can't access https://myq-cloud.com and there is a message about moving to mobile on https://www.mychamberlain.com/
<img width="1522" alt="image" src="https://github.com/hjdhjd/homebridge-myq/assets/16404025/0221bee9-697d-4b62-8552-dfb827c8a224">

**Comment by schmdbrgr** [comment] 2023-09-08 23:57
Same issue.

**Comment by phillipfoose** [comment] 2023-09-08 23:59
Same, I was on an older 2.3.x release and was seeing a separate error, and updating to latest and am seeing this now.

**Comment by WheatGuy** [comment] 2023-09-09 00:00
Same for me.

**Comment by shadowpuck99** [comment] 2023-09-09 00:01
Same here. MyQ app works fine but doesn’t work in HomeKit. Same error.

**Comment by btsubjectdata** [comment] 2023-09-09 00:12
I am getting this error too. 
[08/09/2023, 18:57:51] [homebridge-myq] myQ API error: Forbidden API call. This error is typically due to an offline or unavailable myQ device.
[08/09/2023, 18:59:51] [homebridge-myq] myQ API error: Forbidden API call. This error is typically due to an offline or unavailable myQ device.
[08/09/2023, 19:01:51] [homebridge-myq] myQ API error: Forbidden API call. This error is typically due to an offline or unavailable myQ device.
[08/09/2023, 19:03:51] [homebridge-myq] myQ API error: Forbidden API call. This error is typically due to an offline or unavailable myQ device.
[08/09/2023, 19:05:51] [homebridge-myq] myQ API error: Forbidden API call. This error is typically due to an offline or unavailable myQ device.
[08/09/2023, 19:07:51] [homebridge-myq] myQ API error: Forbidden API call. This error is typically due to an offline or unavailable myQ device.
[08/09/2023, 19:09:51] [homebridge-myq] myQ API error: Forbidden API call. This error is typically due to an offline or unavailable myQ device.
[08/09/2023, 19:11:52] [homebridge-myq] myQ API error: Forbidden API call. This error is typically due to an offline or unavailable myQ device.

**Comment by corey6058** [comment] 2023-09-09 00:19
I can verify the same on my end. Same message in the logs about the API, but myQ app works perfectly fine.

**Comment by mwilliams146** [comment] 2023-09-09 00:22
Same here, same message in the logs about the API.  MyQ App works just fine.  Tried signing out and back in but no luck with authenticating again.

**Comment by schmdbrgr** [comment] 2023-09-09 00:35
Specifying API region west or east seems to restore functionality. But causes issues with an endless spinning wheel for the settings dialog. Changing the setting back to the default “” via config file brings the API error back.

**Comment by fraherjr90** [comment] 2023-09-09 00:41
Getting the same. Reset password, nothing. MyQ app is working.

**Comment by mdjhnson** [comment] 2023-09-09 00:44
> Specifying API region west or east seems to restore functionality. But causes issues with an endless spinning wheel for the settings dialog. Changing the setting back to the default “” via config file brings the API error back.

Thanks @schmdbrgr. Setting the "myQ API Cloud Region" under "Advanced Settings" seems to have resolved my issues.
<img width="864" alt="image" src="https://github.com/hjdhjd/homebridge-myq/assets/16404025/641fc22a-4418-4c34-8e7a-100b4cfcb1d2">

**Comment by jdmtv001** [comment] 2023-09-09 00:48
I can confirm I had the same issue until I made the change to east in the advanced settings. For now it is working as it should.

**Comment by WheatGuy** [comment] 2023-09-09 00:49
> > Specifying API region west or east seems to restore functionality. But causes issues with an endless spinning wheel for the settings dialog. Changing the setting back to the default “” via config file brings the API error back.
> 
> 
> 
> Thanks @schmdbrgr. Setting the "myQ API Cloud Region" under "Advanced Settings" seems to have resolved my issues.
> 
> <img width="864" alt="image" src="https://github.com/hjdhjd/homebridge-myq/assets/16404025/641fc22a-4418-4c34-8e7a-100b4cfcb1d2">
> 
> 

I set my region to west in the plugin settings as well. Working normal as usual now, no lag issues/spinning wheel.

**Comment by corey6058** [comment] 2023-09-09 00:50
Specifying the server location to east or west restored functionality for me. Thanks for the tip.

**Comment by uurf** [comment] 2023-09-09 01:06
> Specifying the server location to east or west restored functionality for me. Thanks for the tip.

same for me. I'm in Pittsburgh, so specifying `east` restored functionality.

**Closed** 2023-09-09 01:11 UTC

**Comment by hjdhjd** [comment] 2023-09-09 01:14
Please stop opening issues related to this. There are multiple other already closed issues on this topic.

To be clear for others who come across this: **myQ API connectivity issues happen, and they are not issues with this plugin, but rather with the myQ API endpoints. Opening issues related to this topic will be summarily closed. I will provide no support for transient (and yes, these are all transient) API issues. All issues related to this topic will be closed. If you’d like to discuss in a community setting, you are welcome to use the Homebridge Discord.**
