### ISSUE TITLE
MyQ garage doors not detected 

### ISSUE THREAD

**Issue by tf64** [hjdhjd/homebridge-myq#474] opened 2021-08-16 04:45 UTC
**Describe The Problem:**

Unable to add my 2 MyQ garage doors using HOOBS/HomeBridge.  When configured with username and password the garage doors are not detected by Homebridge.  The MyQ opener and two door sensors have a solid wifi connection and both function normally using the native MyQ app. 

**To Reproduce:**

Installed HOOBS. Installed myQ Homebridge via the HOOBS plugin page. I have triple checked username and password are correct. 

**Logs:**

```
8/15/2021, 11:17:23 PMmyQ Bridge starting
8/15/2021, 11:17:29 PMmyQ BridgeLoaded plugin 'homebridge-myq'
8/15/2021, 11:17:29 PMmyQ BridgeLoading 1 platforms...
8/15/2021, 11:17:29 PMmyQ BridgeBridge is running on port 51826.
8/15/2021, 11:25:20 PMmyQ BridgeWARNINGunhandled rejection: TypeError: Cannot read property 'getAttribute' of null
```

**Homebridge Configuration:**

```
{
    "platform": "myQ",
    "email": "myemailaddress@email.com",
    "password": "myMyQpassword"
}
```

**Screenshots:**

**Environment:**

* **HOOBS Version:** 4.0.100
* **Homebridge-myQ Plugin Version**: 2.6.3
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 14.7
* **Operating System and OS Version:** 
MacOS 11.4

**Comment by dxdc** [comment] 2021-08-16 13:38
The problem is for everyone I suspect. The myQ HTML must have changed.

This is the problematic line:
https://github.com/hjdhjd/homebridge-myq/blob/951477b98836b3e63a1fad626581961d54a071c3/src/myq-api.ts#L141

```
1|homebridge      | TypeError: Cannot read property 'getAttribute' of null
1|homebridge      |     at myQApi.oauthLogin (/usr/lib/node_modules/homebridge-myq/src/myq-api.ts:141:107)
1|homebridge      |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
1|homebridge      |     at myQApi.getOAuthToken (/usr/lib/node_modules/homebridge-myq/src/myq-api.ts:214:16)
1|homebridge      |     at myQApi.acquireAccessToken (/usr/lib/node_modules/homebridge-myq/src/myq-api.ts:281:19)
1|homebridge      |     at myQApi.refreshAccessToken (/usr/lib/node_modules/homebridge-myq/src/myq-api.ts:323:14)
1|homebridge      |     at myQApi.refreshDevices (/usr/lib/node_modules/homebridge-myq/src/myq-api.ts:357:10)
1|homebridge      |     at myQPlatform.updateAccessories (/usr/lib/node_modules/homebridge-myq/src/myq-platform.ts:283:10)
1|homebridge      |     at /usr/lib/node_modules/homebridge-myq/src/myq-platform.ts:324:14
```

**Comment by hjdhjd** [comment] 2021-08-16 15:55
Closing...I'll post an update a bit later. Thanks for the report!

**Closed by hjdhjd** 2021-08-16 15:55 UTC
