### ISSUE TITLE
Plugin stopped connecting after update to version 2.7.3

### ISSUE THREAD

**Issue by RWSmitty** [hjdhjd/homebridge-myq#611] opened 2022-01-17 17:20 UTC
**Describe The Problem:**
Plugin stopped connecting after update to version 2.7.3

**To Reproduce:**

**Logs:**
[2022-01-17, 11:06:59 a.m.] [myQ] Unknown fetch error: TypeError [ERR_INVALID_URL]: Invalid URL
[2022-01-17, 11:06:59 a.m.] [myQ] myQ API: Unable to complete the OAuth login redirect.

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
{
            "email": "xxxxxx@gmail.com",
            "password": "xxxxxx",
            "name": "myQ",
            "platform": "myQ"
 },
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** v1.3.9
* **Node.js Version:** v16.13.1
* **Homebridge-myQ Plugin Version**:v2.7.3
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone iOS 15.2
* **Operating System and OS Version:** Raspbian GNU/Linux Buster (10)    Npm Version v8.3.0

**Comment by jerry00020001** [comment] 2022-01-17 21:18
Had the exact same errors and issues.

downgraded incrementally from 2.7.3 to 2.6.5.

Issues with [myQ] Unknown fetch error: TypeError [ERR_INVALID_URL]: Invalid URL went away after switching to 2.6.5

**Comment by hjdhjd** [comment] 2022-01-17 21:19
Well that's an intriguing one. Let me take a look...

**Comment by hjdhjd** [comment] 2022-01-17 21:43
This error appears to be on the myQ end, not the plugin end, from what I can see. @jerry00020001 while I appreciate the aggressive downgrade-until-it-works (kudos to you there! 😄 )...would you mind humoring me and trying 2.7.3 again?

**Comment by jerry00020001** [comment] 2022-01-17 22:09
@hjdhjd so I updated to 2.7.3, restarted homebridge and the error returned, then I downgraded back to 2.6.5, restarted homebridge and it started working again. Thanks for looking into this so quickly! @RWSmitty can you try the same thing?

**Comment by hjdhjd** [comment] 2022-01-17 22:13
@jerry00020001 Can you post the erroneous log entries if they differ from the original report?

**Comment by renatobo** [comment] 2022-01-17 22:22
Same here - upgraded to 2.7.3 error

`
[1/17/2022, 1:27:04 PM] [homebridge-myq] Unknown fetch error: TypeError [ERR_INVALID_URL]: Invalid URL
[1/17/2022, 1:29:06 PM] [homebridge-myq] Unknown fetch error: TypeError [ERR_INVALID_URL]: Invalid URL
`

downgraded to 2.6.5 + restarted, it works.

`
[1/17/2022, 2:00:55 PM] [homebridge-myq] myQ API: Successfully connected to the myQ API.
`

**Comment by cmaliwat** [comment] 2022-01-17 22:22
Same issue with 2.7.3. Did the same as previous user, downgraded to 2.6.5, and all is working again.

Same error logs:
`[1/17/2022, 2:16:15 PM] [myQ] Unknown fetch error: TypeError [ERR_INVALID_URL]: Invalid URL
[1/17/2022, 2:16:15 PM] [myQ] myQ API: Unable to complete the OAuth login redirect.`

**Comment by hjdhjd** [comment] 2022-01-17 22:23
Thanks...locking this issue for now. I'll look into it. Don't want to pollute it with lots of corroboratory posts.

**Comment by hjdhjd** [comment] 2022-01-17 22:43
Problem identified and resolution inflight..will update this shortly. Thanks.

**Comment by hjdhjd** [comment] 2022-01-17 22:53
Unlocking this thread... @jerry00020001 can you try reinstalling 2.7.3...things should work now.

**Comment by grantmd** [comment] 2022-01-17 23:01
I've been following this issue since I've had the same problem. Never downgraded or anything, but I can confirm that after uninstalling and re-installing the plugin the issue is fixed for me.

**Comment by hjdhjd** [comment] 2022-01-17 23:01
The issue is an upstream dependency...I've ensured we use a prior version of the dependency that works until the upstream can resolve. All should be right with the world. Closing. 😄

**Closed by hjdhjd** 2022-01-17 23:01 UTC

**Comment by jerry00020001** [comment] 2022-01-17 23:24
yup 2.7.4 works!! thanks again, you're awesome!
